# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: SUT_AutoReport_Python

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 15 5-9/2 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: SignIn
      run: |
        python3 ./main.py
      env:
        UA: ${{ secrets.UA }}
        UP: ${{ secrets.UP }}
        MQ: ${{ secrets.MQ }}
        SF: ${{ secrets.SF }}
        JW: ${{ secrets.JW }}
        SJ: ${{ secrets.SJ }}
        JS: ${{ secrets.JS }}
        ZA: ${{ secrets.ZA }}
        ZB: ${{ secrets.ZB }}
        SK: ${{ secrets.SK }}








